export type ExhibitionLead = {
  id: string; email: string | null; kakaoEmail: string | null; name: string | null; phone: string | null; companyName: string | null; jobTitle: string | null; favoriteFabrics: string | null; provider: string | null; profileCompleted: boolean; createdAt: string | null;
  registrationType: "catalog" | "dian" | "saekdong" | "other"; address: string | null; swatches: string[]; inquiry: string | null;
};
type CatalogCustomerRow = { id:string; email:string|null; kakao_email:string|null; name:string|null; phone:string|null; company_name:string|null; position:string|null; favorite_fabrics:string|null; provider:string|null; profile_completed:boolean; created_at:string|null };
type RegistrationRow = { id:string; email:string|null; phone:string|null; company_name:string|null; job_title:string|null; source:string|null; source_record_id:string|null; created_at:string|null; marketing_consent:boolean|null };
export type CatalogCustomerDateFilter = { start?: string; end?: string; registrationType?: ExhibitionLead['registrationType'] };
function config(){ const url=process.env.SUPABASE_FABRIC_URL||process.env.SUPABASE_URL; const key=process.env.SUPABASE_FABRIC_SERVICE_ROLE_KEY||process.env.SUPABASE_SERVICE_KEY; return url&&key?{url:url.replace(/\/$/,''),key}:null; }
function headers(key:string):HeadersInit{return {apikey:key,Authorization:`Bearer ${key}`};}
function kstStartOfDay(date:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return null;const result=new Date(`${date}T00:00:00+09:00`);return Number.isNaN(result.getTime())?null:result;}
function kstEndExclusive(date:string){const result=kstStartOfDay(date);if(!result)return null;result.setUTCDate(result.getUTCDate()+1);return result;}
function dateQuery(filter:CatalogCustomerDateFilter){const query=new URLSearchParams({order:'created_at.desc'});const start=filter.start?kstStartOfDay(filter.start):null;const end=filter.end?kstEndExclusive(filter.end):null;if(start)query.append('created_at',`gte.${start.toISOString()}`);if(end)query.append('created_at',`lt.${end.toISOString()}`);return query;}
function metadata(value:string|null){try{const data=JSON.parse(value||'{}') as {name?:unknown;address?:unknown;selectedSwatches?:unknown;inquiry?:unknown;registrationType?:unknown};return {name:typeof data.name==='string'?data.name:null,address:typeof data.address==='string'?data.address:null,swatches:Array.isArray(data.selectedSwatches)?data.selectedSwatches.filter((v):v is string=>typeof v==='string'):[],inquiry:typeof data.inquiry==='string'?data.inquiry:null,registrationType:data.registrationType==='saekdong'?'saekdong':data.registrationType==='dian'?'dian':'other'};}catch{return {name:null,address:null,swatches:[],inquiry:null,registrationType:'other' as const};}}
export async function getCatalogCustomers(filter:CatalogCustomerDateFilter={}):Promise<ExhibitionLead[]>{const env=config();if(!env)return[];const query=dateQuery(filter);query.set('select','id,email,kakao_email,name,phone,company_name,position,favorite_fabrics,provider,profile_completed,created_at');const response=await fetch(`${env.url}/rest/v1/catalog_customers?${query}`,{headers:headers(env.key),cache:'no-store'});if(!response.ok)throw new Error('카탈로그 가입 고객 정보를 불러오지 못했습니다.');const rows=await response.json() as CatalogCustomerRow[];return rows.map(r=>({id:`catalog:${r.id}`,email:r.email,kakaoEmail:r.kakao_email,name:r.name,phone:r.phone,companyName:r.company_name,jobTitle:r.position,favoriteFabrics:r.favorite_fabrics,provider:r.provider,profileCompleted:r.profile_completed,createdAt:r.created_at,registrationType:'catalog',address:null,swatches:[],inquiry:null}));}
export async function getExhibitionCustomers(filter:CatalogCustomerDateFilter={}):Promise<ExhibitionLead[]>{const env=config();if(!env)return[];const query=dateQuery(filter);query.set('select','id,email,phone,company_name,job_title,source,source_record_id,created_at,marketing_consent');query.set('source','in.(dian_customer_registration,saekdong_customer_registration)');const response=await fetch(`${env.url}/rest/v1/exhibition_leads?${query}`,{headers:headers(env.key),cache:'no-store'});if(!response.ok)throw new Error('전시 고객 정보를 불러오지 못했습니다.');const rows=await response.json() as RegistrationRow[];return rows.map(r=>{const m=metadata(r.source_record_id);const type=r.source==='saekdong_customer_registration'?'saekdong':'dian';return {id:`exhibition:${r.id}`,email:r.email,kakaoEmail:null,name:m.name,phone:r.phone,companyName:r.company_name,jobTitle:r.job_title,favoriteFabrics:null,provider:null,profileCompleted:!!r.marketing_consent,createdAt:r.created_at,registrationType:type,address:m.address,swatches:m.swatches,inquiry:m.inquiry};});}
export async function getAllExhibitionCustomers(filter:CatalogCustomerDateFilter={}){const [catalog,exhibition]=await Promise.all([getCatalogCustomers(filter),getExhibitionCustomers(filter)]);const all=[...catalog,...exhibition];const filtered=filter.registrationType?all.filter(lead=>lead.registrationType===filter.registrationType):all;return filtered.sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''));}
