import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const source = readFileSync('/Users/dian/CFO/src/components/exhibition/Hiem2026Planner.tsx', 'utf8')

assert.match(source, /aria-label="모바일 현장 기록 창"/)
assert.match(source, /fixed inset-0/)
assert.match(source, /onClose=\{\(\) => setSelectedId\(null\)\}/)
assert.match(source, /notes\[booth\.id\]\?\.status/)
assert.match(source, /미팅 완료/)
assert.match(source, /grid-cols-3/)
assert.match(source, /overflow-x-auto/)
assert.match(source, /sm:grid-cols-2/)
assert.match(source, /2026 상하이 INTERTEXTILE/)
assert.match(source, /새 업체 추가/)
assert.match(source, /사진 업로드/)
assert.match(source, /명함 업로드/)
assert.match(source, /새 업체 분류/)
assert.match(source, /새 업체 카드/)
assert.match(source, /구매요청 샘플/)
assert.match(source, /draft\.photo/)
assert.match(source, /사진 업로드.*미팅 메모/s)
assert.match(source, /multiple/)
assert.match(source, /photos\?: string\[\]/)
assert.match(source, /Array\.from\(files/)
assert.match(source, /웹사이트/)
assert.match(source, /재고관리/)
assert.match(source, /websiteChecked/)
assert.match(source, /inventoryChecked/)
assert.match(source, /사진 크게 보기/)
assert.match(source, /사진 삭제/)
assert.match(source, /removePhoto\(index\)/)
console.log('HIEM mobile detail drawer source test passed')
